from odoo import http
from odoo.http import request

RENDER_VALUES = {
    "report": "account.report(11,)",
    "report_title": "General Ledger",
    "options": {
        "companies": [
            {
                "name": "My Company",
                "id": 1,
                "currency_id": 1
            }
        ],
        "variants_source_id": 11,
        "has_inactive_variants": False,
        "available_variants": [
            {
                "id": 11,
                "name": "General Ledger",
                "country_id": False
            }
        ],
        "selected_variant_id": 11,
        "sections_source_id": 11,
        "sections": [],
        "has_inactive_sections": False,
        "report_id": 11,
        "allow_domestic": True,
        "fiscal_position": "all",
        "available_vat_fiscal_positions": [],
        "date": {
            "string": "Apr 2025",
            "period_type": "month",
            "currency_table_period_key": "2025-04-01_2025-04-30",
            "mode": "range",
            "date_from": "2025-04-01",
            "date_to": "2025-04-30",
            "filter": "this_month"
        },
        "available_horizontal_groups": [],
        "selected_horizontal_group_id": None,
        "export_mode": "print",
        "journals": [
            {
                "id": 6,
                "model": "account.journal",
                "name": "Bank",
                "selected": False,
                "title": "Bank - BNK1",
                "type": "bank",
                "visible": True
            },
            {
                "id": 5,
                "model": "account.journal",
                "name": "Cash Basis Taxes",
                "selected": False,
                "title": "Cash Basis Taxes - CABA",
                "type": "general",
                "visible": True
            },
            {
                "id": 4,
                "model": "account.journal",
                "name": "Exchange Difference",
                "selected": False,
                "title": "Exchange Difference - EXCH",
                "type": "general",
                "visible": True
            },
            {
                "id": 3,
                "model": "account.journal",
                "name": "Miscellaneous Operations",
                "selected": False,
                "title": "Miscellaneous Operations - MISC",
                "type": "general",
                "visible": True
            },
            {
                "id": 2,
                "model": "account.journal",
                "name": "Purchases",
                "selected": False,
                "title": "Purchases - BILL",
                "type": "purchase",
                "visible": True
            },
            {
                "id": 1,
                "model": "account.journal",
                "name": "Sales",
                "selected": False,
                "title": "Sales - INV",
                "type": "sale",
                "visible": True
            }
        ],
        "selected_journal_groups": {},
        "name_journal_group": "All Journals",
        "all_entries": False,
        "aml_ir_filters": [],
        "buttons": [
            {
                "name": "PDF",
                "sequence": 10,
                "action": "export_file",
                "action_param": "export_to_pdf",
                "file_export_type": "PDF",
                "branch_allowed": True,
                "always_show": True
            },
            {
                "name": "XLSX",
                "sequence": 20,
                "action": "export_file",
                "action_param": "export_to_xlsx",
                "file_export_type": "XLSX",
                "branch_allowed": True,
                "always_show": True
            }
        ],
        "hide_0_lines": False,
        "loading_call_number": 2,
        "multi_currency": True,
        "unreconciled": False,
        "rounding_unit": "decimals",
        "rounding_unit_names": {
            "decimals": [
                ".$",
                ""
            ],
            "units": [
                "$",
                ""
            ],
            "thousands": [
                "K$",
                "Amounts in Thousands"
            ],
            "millions": [
                "M$",
                "Amounts in Millions"
            ]
        },
        "search_bar": True,
        "unfold_all": True,
        "unfolded_lines": [],
        "column_headers": [
            [
                {
                    "name": "Apr 2025",
                    "forced_options": {
                        "date": {
                            "string": "Apr 2025",
                            "period_type": "month",
                            "currency_table_period_key": "2025-04-01_2025-04-30",
                            "mode": "range",
                            "date_from": "2025-04-01",
                            "date_to": "2025-04-30",
                            "filter": "this_month"
                        }
                    }
                }
            ]
        ],
        "columns": [
            {
                "name": "Date",
                "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                "expression_label": "date",
                "sortable": False,
                "figure_type": "date",
                "blank_if_zero": False,
                "style": "text-align: center; white-space: nowrap;"
            },
            {
                "name": "Communication",
                "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                "expression_label": "communication",
                "sortable": False,
                "figure_type": "string",
                "blank_if_zero": False,
                "style": "text-align: center; white-space: nowrap;"
            },
            {
                "name": "Partner",
                "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                "expression_label": "partner_name",
                "sortable": False,
                "figure_type": "string",
                "blank_if_zero": False,
                "style": "text-align: center; white-space: nowrap;"
            },
            {
                "name": "Debit",
                "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                "expression_label": "debit",
                "sortable": False,
                "figure_type": "monetary",
                "blank_if_zero": False,
                "style": "text-align: center; white-space: nowrap;"
            },
            {
                "name": "Credit",
                "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                "expression_label": "credit",
                "sortable": False,
                "figure_type": "monetary",
                "blank_if_zero": False,
                "style": "text-align: center; white-space: nowrap;"
            },
            {
                "name": "Balance",
                "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                "expression_label": "balance",
                "sortable": False,
                "figure_type": "monetary",
                "blank_if_zero": False,
                "style": "text-align: center; white-space: nowrap;"
            }
        ],
        "column_groups": {
            "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))": {
                "forced_options": {
                    "date": {
                        "string": "Apr 2025",
                        "period_type": "month",
                        "currency_table_period_key": "2025-04-01_2025-04-30",
                        "mode": "range",
                        "date_from": "2025-04-01",
                        "date_to": "2025-04-30",
                        "filter": "this_month"
                    }
                },
                "forced_domain": []
            }
        },
        "show_debug_column": False,
        "show_horizontal_group_total": None,
        "order_column": None,
        "hierarchy": False,
        "display_hierarchy_filter": False,
        "prefix_groups_threshold": 4000,
        "currency_table": {
            "type": "monocurrency",
            "periods": {
                "2025-04-01_2025-04-30": {
                    "from": "2025-04-01",
                    "to": "2025-04-30"
                }
            }
        },
        "readonly_query": True,
        "css_custom_class": ""
    },
    "table_start": "<tbody>",
    "table_end": "\n                </tbody></table></div>\n                <div style=\"page-break-after: always\"></div>\n                <div class=\"d-flex align-items-start\">\n                <table class=\"o_table\">\n            ",
    "column_headers_render_data": {
        "level_colspan": [
            6
        ],
        "level_repetitions": [
            1
        ],
        "custom_subheaders": []
    },
    "custom_templates": {},
    "base_url": "http://localhost:8069",
    "lines": [
        {
            "id": "~account.report~11|~account.account~7",
            "name": "121000 Account Receivable",
            "columns": [
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "date",
                    "figure_type": "date",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": None,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": ""
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "communication",
                    "figure_type": "string",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": None,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": ""
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "partner_name",
                    "figure_type": "string",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": None,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": ""
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "debit",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": 432903.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a0432,903.00"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "credit",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": 0.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a00.00"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "balance",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": 432903.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a0432,903.00"
                }
            ],
            "level": 1,
            "unfoldable": True,
            "unfolded": True,
            "expand_function": "_report_expand_unfoldable_line_general_ledger"
        },
        {
            "id": "~account.report~11|~account.account~7|2025-04-24~account.move.line~2",
            "caret_options": "account.move.line",
            "parent_id": "~account.report~11|~account.account~7",
            "name": "INV/2025/00001",
            "columns": [
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "date",
                    "figure_type": "date",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": "2025-04-24",
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "04/24/2025"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "communication",
                    "figure_type": "string",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": "INV/2025/00001",
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "INV/2025/00001"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "partner_name",
                    "figure_type": "string",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": "My Company",
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "My Company"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "debit",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": 432903.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a0432,903.00"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "credit",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": 0.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a00.00"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "balance",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": 432903.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a0432,903.00"
                }
            ],
            "level": 3,
            "is_draft": False
        },
        {
            "id": "~account.report~11|~account.account~7|total~~",
            "name": "Total 121000 Account Receivable",
            "columns": [
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "date",
                    "figure_type": "date",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": None,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": ""
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "communication",
                    "figure_type": "string",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": None,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": ""
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "partner_name",
                    "figure_type": "string",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": None,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": ""
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "debit",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": 432903.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a0432,903.00"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "credit",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": 0.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a00.00"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "balance",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": 432903.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a0432,903.00"
                }
            ],
            "level": 1,
            "unfoldable": False,
            "unfolded": False,
            "expand_function": "_report_expand_unfoldable_line_general_ledger",
            "parent_id": "~account.report~11|~account.account~7",
            "caret_options": None,
            "action_id": None,
            "page_break": False
        },
        {
            "id": "~account.report~11|~account.account~27",
            "name": "400000 Product Sales",
            "columns": [
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "date",
                    "figure_type": "date",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": None,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": ""
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "communication",
                    "figure_type": "string",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": None,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": ""
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "partner_name",
                    "figure_type": "string",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": None,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": ""
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "debit",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": 0.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a00.00"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "credit",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": 432903.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a0432,903.00"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "balance",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": -432903.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a0-432,903.00"
                }
            ],
            "level": 1,
            "unfoldable": True,
            "unfolded": True,
            "expand_function": "_report_expand_unfoldable_line_general_ledger"
        },
        {
            "id": "~account.report~11|~account.account~27|2025-04-24~account.move.line~1",
            "caret_options": "account.move.line",
            "parent_id": "~account.report~11|~account.account~27",
            "name": "INV/2025/00001",
            "columns": [
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "date",
                    "figure_type": "date",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": "2025-04-24",
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "04/24/2025"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "communication",
                    "figure_type": "string",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": None,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": ""
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "partner_name",
                    "figure_type": "string",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": "My Company",
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "My Company"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "debit",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": 0.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a00.00"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "credit",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": 432903.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a0432,903.00"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "balance",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": -432903.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a0-432,903.00"
                }
            ],
            "level": 3,
            "is_draft": False
        },
        {
            "id": "~account.report~11|~account.account~27|total~~",
            "name": "Total 400000 Product Sales",
            "columns": [
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "date",
                    "figure_type": "date",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": None,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": ""
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "communication",
                    "figure_type": "string",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": None,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": ""
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "partner_name",
                    "figure_type": "string",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": None,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": ""
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "debit",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": 0.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a00.00"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "credit",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": 432903.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a0432,903.00"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": None,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "balance",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": -432903.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a0-432,903.00"
                }
            ],
            "level": 1,
            "unfoldable": False,
            "unfolded": False,
            "expand_function": "_report_expand_unfoldable_line_general_ledger",
            "parent_id": "~account.report~11|~account.account~27",
            "caret_options": None,
            "action_id": None,
            "page_break": False
        },
        {
            "id": "~account.report~11|total~~",
            "name": "Total",
            "level": 1,
            "columns": [
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": False,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "date",
                    "figure_type": "date",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": None,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": ""
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": False,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "communication",
                    "figure_type": "string",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": None,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": ""
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": False,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "partner_name",
                    "figure_type": "string",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": None,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": ""
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": False,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "debit",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": 432903.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a0432,903.00"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": False,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "credit",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": False,
                    "no_format": 432903.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a0432,903.00"
                },
                {
                    "auditable": False,
                    "blank_if_zero": False,
                    "column_group_key": "(('forced_options', (('date', (('currency_table_period_key', '2025-04-01_2025-04-30'), ('date_from', '2025-04-01'), ('date_to', '2025-04-30'), ('filter', 'this_month'), ('mode', 'range'), ('period_type', 'month'), ('string', 'Apr 2025'))),)), ('horizontal_groupby_element', ()))",
                    "currency": False,
                    "currency_symbol": "$",
                    "digits": 1,
                    "expression_label": "balance",
                    "figure_type": "monetary",
                    "green_on_positive": False,
                    "has_sublines": False,
                    "is_zero": True,
                    "no_format": 0.0,
                    "format_params": {},
                    "report_line_id": None,
                    "sortable": False,
                    "comparison_mode": None,
                    "name": "$\u00a00.00"
                }
            ]
        }
    ],
    "annotations": []
}


class TestActionReportController(http.Controller):

    @http.route(['/yo'], type='http', auth='public', csrf=False)
    def yo(self):
        pdf = request.env['ir.actions.report']._render_qweb_pdf(
            'test_action_report.test_report_action',
            data=RENDER_VALUES,
        )[0]
        pdfhttpheaders = [('Content-Type', 'application/pdf'), ('Content-Length', len(pdf))]
        return request.make_response(pdf, headers=pdfhttpheaders)
